jake_tran_vatican_script = '''
Religion can be an incredibly profitable business if done right. And there's no better example of this than the Vatican, the world's smallest sovereign nation at just 0.27 square kilometers. It is home to the wealthiest religion on the planets, the Catholic church. For decades, the Catholic Church has been haunted by scandal after scandal after scandal with more than 1.3 billion members worldwide. It is the second biggest religion in the world, and this entire empire of vast unimaginable wealth is based off of your donations. 

But the Catholic church is clever. If people knew just how wealthy they are, no one would continue donating to them. That's why they keep all their true finances very close to their chest, careful to not let the public ever peer into the true financial state of the church. That's why in 2021, the Catholic Church is winding that apparently they're low on reserves, running a deficit and are in desperate need of your donations. When in Australia alone, they're worth at least $30 billion. That's more than what Starbucks is worth around the world. And thanks to some simple math, we can get a rough estimate of how much wealth the Catholic Church really has. So the Catholic Church is worth around 30 billion in Australia. There's around five and a half million Catholics in Australia. That means the Catholic Church is able to extract an average of around $5,454 per user. There are 372 million Catholics in Europe, the us, Canada, and Australia combined. So $5,454 per Catholic Times 372 million Catholics means that the Catholic Church has a little over $2 trillion in wealth, 

And that's just from the main Western countries. That means the Catholic Church is in the same league as companies and love like Apple, Microsoft, the Saudi Arabian Oil company, Amazon and Alphabet. Let's say on that $2 trillion, they're able to get a conservative return of 3 percent. For context, the stock market typically returns 10 percent, $2 trillion at just 3 percent, gives 'em $60 billion every single year. Tax-free, theoretically, of course. But what do they tell the public that in 2018, apparently they only profited a measly $20 million, nowhere near even 1 billion. And at the center of all of this is the Vatican Bank, God's bankers. Today, it's probably better to think of the Vatican as a combination of the Federal Reserve, an offshore bank, and a hedge fund compared to just being the headquarters of Catholicism. The Vatican is the ultimate corporation that has stood the Tesla time like no other. And this is how it's done. 

Centuries before the Catholic Church became a capitalist holding company, the Vatican was a secular empire, meaning that its existence wasn't directly connected to Catholicism as it is today. The Popes were the kings of the Vatican, and they also acted as the supreme leaders of the Roman Church in Italy. Popes believed that God had chosen them to reign over all the other leaders of the world. During the time of the Pope Kings, the Vatican controlled over 15,000 square miles of land in Italy called the Papal states vastly bigger than the tiny area the Vatican City occupies today. All this land was important because building palaces and running one of the most luxurious courts in Europe was expensive. And what better way to continue your life of luxury than by taxing the people you rule over, just like the corrupt governments of today. People's taxes in the sixth and seventh century went to maintaining the lifestyles of the Pope Kings and their sidekicks, also known as the Cardinals. 

Over time, the taxes just weren't enough for the lavish lifestyle that guys in charge had come to expect. But there was a problem. The Pope was already taxing the Popal states charging fees to trade and do business, selling most of the region's agricultural products, and none of it was enough. He needed a new way to make money fast. Around the sixth century, the Vatican leadership suddenly had a brilliant plan. They were already selling most of the Papapa state's natural resources to make money, but there were only so many grapes or vegetables to exports. But what if the Pope and his cardinals has something to sell that was incredibly valuable and would never run out? They would be able to make infinite amounts of money. So the plan was simple. Since the Pope was God's representative on Earth and he had thousands of members in his church, what if he could sell 'em away to reduce the amount of punishment they would receive for their sins? 

After all years of penance and fear of purgatory had made people terrified of God's wrath. So paying just a little bit of extra money so only wouldn't burden in hell as long was a very good deal. So the church started selling indulgences little tickets that promised God wouldn't punish them too much for whatever they did wrong. Small sins were cheaper to get indulgences for. While bigger sins were obviously more expensive, even though it wasn't the original plan, indulgences became people's get out of jail free cards, except they actually had to pay for them. It was a cash cow unlike anything the Vatican had ever seen before. Sure, hundreds of church officials were abusing their right to sell indulgences, but with millions flowing into the church treasury, who was the Pope to complain, after all the prosperity of the church was God's will, the sale of indulgences went on for more than a thousand years. During this time, the church and the Pope got wealthier and wealthier. But then starting with the 1789 French Revolution, things started to go downhill. First, Napoleon demanded millions in tribute from the Vatican each year. Then other leaders of Europe started taxing the Vatican's money as well. The Pope called taxing the Vatican, the work of the devil. But it didn't change the fact that the endless stream of money the Pope had been enjoying were quickly drying up. Something had to be done 

When European states asking the Vatican for more and more money. Taxes on the Papapa states kept going up. And like any 19th century state with corrupt leaders in climbing taxes, the people rebelled. In 1848, crowd stormed the Vatican city and murdered the Papal Prime Minister. The people of the papal states were tired of being treated as a cash reserve, and the Vatican went into massive debts. It was two years behind on bills. Taxes were almost non-existence, and even the sale of indulgences had nose dived the Pope in charge. I tried appealing to the masses, allowing more freedom of speech and releasing more than a thousand political prisoners, but it was too little, too late, desperate to keep the Vatican and the church going. The Pope had a difficult decision to make. He would go to the Rothchilds for help. Yes, those rothchilds. Being a Jewish family business, the Pope had to swallow a lot of pride to get into their debts. 

But his lifestyle and wealth was more important than his pride. So the Rothschilds let the Vatican 50 million francs around $10 million to cover the Vatican's budget for an entire year. But then in 1870, the Italians invaded Rome and brought an end to the Vatican's control of the papal states. Even making deals with heathens couldn't save the Vatican from financial ruin. The 15,000 square miles, the Vatican control was reduced to 0.17. The thousands of subjects the Vatican could tax have fallen to around 700 people who've lived at the courts, the massive papal empire have fallen and became what we now know today as the Vatican city 

Around 60 Italian family state, loyal to the Pope, they were known as the Black Nobles. The Vatican was at a crossroads, and this led to the first ever Catholic investments into secular businesses. The Pope started investing money into Roman real estate, and luckily, he caught the front end of the real estate boom. And for a while, his investments were a big success. Most of the black nobles just followed the church's example and invested in the same properties as the Pope did, and they got rich too. But then in 1887, the property market crashed and the Vatican was back to square one, looking for a new way to make money. So the church started asking for donations or Peters pence, as they called it. They were in the important business of saving souls. And if regular Catholic church members wanted to get in on the salvation, all they had to do was donate some money to the church. And the church was back in business and started investing more than ever into secular businesses. And then just like most of the major global corporations we talked about before, the World Wars came along and the church saw an opportunity to profit like never before. 

Just as World War I broke out, a new pope took control of the Vatican, donations plummeted, and so did the Vatican's income again. And for a while, the new Pope tried to get Italy to stay neutral in the war, hoping that it would keep their investments in Italy safe. But in 1915, the Italians declared war on Germany and joined the Allies, leaving the Pope desperately looking for a way to keep his revenues up. So the Vatican rented one of its properties in Rome to an arms manufacturer that sold to Germany. Yes, the Vatican was indirectly making money, selling weapons of war to the other side of the war. When the public eventually found out about the arms dealing, the church said it was in complete shock and never knew about what its tenant was doing. But it was all in vain because by 1933, the Vatican was losing around a hundred million lira a year desperate not to go under. 

The Pope finally gave in and got a real financial advisor who helped keep the Vatican out of the gutters by making a lot of diverse investments and the most profitable time in Vatican. History was only just starting when World War II hit. Instead of staying out politics and focusing on religion like he did in World War I, the Pope went all in and took the German side. The Vatican had become friendly with the fascist leader of Italy. Mussolini and Germany seemed to be a similar choice, and in exchange for their supports, the third Reich would deduct eight to 10 percent of Catholic Germans wages to be sent directly to the Vatican. The third Ree was taxing Catholics on the Vatican's behalf. The church usually had trouble getting people to pay on their own free will. So automatically taking 10 percent of all Catholics in Germany's monthly wage did a lot to boost the Vatican economy. 

The Germans and the Vatican got so friendly that when the sending Pope died, there were rumors that Hitler could pay 3 million gold Reich marks or $12.6 million at the time and pick whoever he wanted to be. The next Pope, the new Pope, although actually not picked by Hitler, seemed happy to keep a good relationship with Germany and even held a grand reception for Hitler's 50th birthday. Money was once again flowing into the Vatican City, but there was a new problem. All the Vatican's transactions and money was kept in Western banks and Europe, which meant that most of it could be traced or even frozen, and it wouldn't be long before the Allies found out just how much of the church's money was coming from Germany, which would mean instant blacklisting. So the Pope's financial advisor came up with a new plan, build a bank in the Vatican. 

After all, the Vatican is its own country, so why shouldn't it have a national bank? So this bank with this long name or IOR was born, it only had one branch inside the Vatican City, and it wasn't on anyone's blacklist, which meant it was free from wartime regulations. The new Vatican Bank could operate anywhere in the world without showing profits, annual reports, balance sheets, or where its money came from. And it only had one shareholder, the Pope. Now, the Vatican could take money from whoever they wanted, deposit it into their own bank, and never leave a single paper trail behind. And it didn't take people long to see how the Vatican Bank could be useful to them from all over Europe. Rich Italians were now depositing their money into the Vatican Bank by sending an employee over the street with a suitcase full of cash. But it wasn't only the Italians. Eventually the OSS, which was the precursor to the ccia A found out that even Hitler was making regular deposits into the Vatican Bank using a Swiss bank as a middleman. Out of all the clever business moves we've seen on this channel, this has got to be one of my favorites. 

Near the end of World War ii, the bad kid was so deep in bed with the Germans. They would even take money from the life insurance policies of Jews that were sent to camps. When the families came asking for the money, they rightfully deserved, the insurance companies would ask to see a death certificate they knew no one could actually get. So they kept the money and you guessed it deposited that money into the Vatican Bank. And it wasn't just the Germans in the days of the Italian mafia. Anyone with drug money, racketeering money, or any other illegal funds could deposit their cash at the Vatican Bank and know it can never be traced. And their deposits never made public. The Vatican Bank became known as the place to launder or hide your money. And with all that notorious reputation came a lot of government attention. 

But instead of closing down the bank for its illegal or unethical activities, the Italian government thought they could profit too and decided that all the regional banks owned by the Vatican will have to start paying tax by the mid fifties. The church has 600 million members and dependent on donations for most of its money and investments. So when a report came out that the Vatican $13 billion in liquid investments, the Pope quickly corrected them saying that it was probably closer to 500 million, less than 4 percent of the estimate. But soon the church would run into more trouble with donations, but it wouldn't be because of people finding out just how much money they had. Around the late 20th century, reports started going around about how priests abuse children. I'm sure you've seen at least one of these stories in the news. 

Obviously, the idea that the priesthood, the people who were supposed to be the leaders of the churches were hurting kids, was bad news for donations. The Vatican had to do everything in its power to keep people quiet. If the church admitted to knowing about the abuse, it would be the end of them. So by January, 2002, the Catholic Church had already paid out around $175 million in settlements to families from Australia to Europe. Instead of apologizing, the Pope made excuses, which meant even more lawsuits were filed, and even more money was paid out. By 2014, that $175 million in settlements had turned into more than 3 billion donations dropped. But as usual, the Vatican had a plan. In 2013, after the death of the sitting Pope, they decided to make a radical change. They would elect a new modern Pope, one who would appeal to the masses promise reform and actually make it seem like he's making change. So Pope Francis took power and set up to fix the church's reputation, and it worked 

What the help of a Pope who could appeal to the masses and make it seem like he really cared about the people. The Vatican was able to make everyone conveniently forget about what they had done to get so much money and power in the first place. Which leads us to today where the church has more than 1.2 billion followers based on my estimations at the beginning of this video, they have around $2 trillion in wealth, and their number one call for donations is yet again that they're on the verge of bankruptcy. Even though one Catholic official in New York City alone is the largest landowner in Manhattan. Proving once again that when you have just the right combination of guilt, fear, and the promise of eternal life, religion can be one of the most lucrative businesses in the world. 

This is how the Vatican really operates and why this is probably the first time you're hearing about it. They're never going to publicly review their motives and intentions, so you can learn from them. But that is exactly what we're doing here, going over all the things they'll never be able to teach you in business school. '''